# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'show_download.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_show_download(object):
    def setupUi(self, show_download):
        show_download.setObjectName("show_download")
        show_download.setWindowModality(QtCore.Qt.WindowModal)
        show_download.resize(260, 500)
        self.centralwidget = QtWidgets.QWidget(show_download)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        self.centralwidget.setFont(font)
        self.centralwidget.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(8, 8, 8, 8)
        self.verticalLayout.setObjectName("verticalLayout")
        self.uiTableWidget_downloading = QtWidgets.QTableWidget(self.centralwidget)
        self.uiTableWidget_downloading.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.uiTableWidget_downloading.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.uiTableWidget_downloading.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.uiTableWidget_downloading.setCornerButtonEnabled(False)
        self.uiTableWidget_downloading.setObjectName("uiTableWidget_downloading")
        self.uiTableWidget_downloading.setColumnCount(2)
        self.uiTableWidget_downloading.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.uiTableWidget_downloading.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.uiTableWidget_downloading.setHorizontalHeaderItem(1, item)
        self.uiTableWidget_downloading.horizontalHeader().setHighlightSections(False)
        self.uiTableWidget_downloading.horizontalHeader().setStretchLastSection(True)
        self.uiTableWidget_downloading.verticalHeader().setVisible(False)
        self.uiTableWidget_downloading.verticalHeader().setHighlightSections(False)
        self.verticalLayout.addWidget(self.uiTableWidget_downloading)
        show_download.setCentralWidget(self.centralwidget)

        self.retranslateUi(show_download)
        QtCore.QMetaObject.connectSlotsByName(show_download)

    def retranslateUi(self, show_download):
        _translate = QtCore.QCoreApplication.translate
        show_download.setWindowTitle(_translate("show_download", "下载列表"))
        item = self.uiTableWidget_downloading.horizontalHeaderItem(0)
        item.setText(_translate("show_download", "下载项"))
        item = self.uiTableWidget_downloading.horizontalHeaderItem(1)
        item.setText(_translate("show_download", "下载状态"))
