# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'impanel.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ImPanel(object):
    def setupUi(self, ImPanel):
        ImPanel.setObjectName("ImPanel")
        ImPanel.setWindowModality(QtCore.Qt.ApplicationModal)
        ImPanel.resize(116, 45)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        ImPanel.setFont(font)
        self.verticalLayout = QtWidgets.QVBoxLayout(ImPanel)
        self.verticalLayout.setObjectName("verticalLayout")
        self.help_panel = QtWidgets.QLabel(ImPanel)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        self.help_panel.setFont(font)
        self.help_panel.setText("")
        self.help_panel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.help_panel.setOpenExternalLinks(True)
        self.help_panel.setObjectName("help_panel")
        self.verticalLayout.addWidget(self.help_panel)

        self.retranslateUi(ImPanel)
        QtCore.QMetaObject.connectSlotsByName(ImPanel)

    def retranslateUi(self, ImPanel):
        _translate = QtCore.QCoreApplication.translate
        ImPanel.setWindowTitle(_translate("ImPanel", "关于"))
