# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'choose_env.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_choose_env(object):
    def setupUi(self, choose_env):
        choose_env.setObjectName("choose_env")
        choose_env.setWindowModality(QtCore.Qt.ApplicationModal)
        choose_env.resize(396, 262)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        choose_env.setFont(font)
        self.verticalLayout = QtWidgets.QVBoxLayout(choose_env)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lw_env_list = QtWidgets.QListWidget(choose_env)
        self.lw_env_list.setObjectName("lw_env_list")
        self.verticalLayout.addWidget(self.lw_env_list)

        self.retranslateUi(choose_env)
        QtCore.QMetaObject.connectSlotsByName(choose_env)

    def retranslateUi(self, choose_env):
        _translate = QtCore.QCoreApplication.translate
        choose_env.setWindowTitle(_translate("choose_env", "选择Python环境"))
