# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'InformationPanel.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_InformationPanel(object):
    def setupUi(self, InformationPanel):
        InformationPanel.setObjectName("InformationPanel")
        InformationPanel.setWindowModality(QtCore.Qt.ApplicationModal)
        InformationPanel.resize(116, 45)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        InformationPanel.setFont(font)
        self.verticalLayout = QtWidgets.QVBoxLayout(InformationPanel)
        self.verticalLayout.setObjectName("verticalLayout")
        self.help_panel = QtWidgets.QLabel(InformationPanel)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        self.help_panel.setFont(font)
        self.help_panel.setText("")
        self.help_panel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.help_panel.setOpenExternalLinks(True)
        self.help_panel.setObjectName("help_panel")
        self.verticalLayout.addWidget(self.help_panel)

        self.retranslateUi(InformationPanel)
        QtCore.QMetaObject.connectSlotsByName(InformationPanel)

    def retranslateUi(self, InformationPanel):
        _translate = QtCore.QCoreApplication.translate
        InformationPanel.setWindowTitle(_translate("InformationPanel", "关于"))
