# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PyiToolChoosePyEnv.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PyiToolChoosePyEnv(object):
    def setupUi(self, PyiToolChoosePyEnv):
        PyiToolChoosePyEnv.setObjectName("PyiToolChoosePyEnv")
        PyiToolChoosePyEnv.setWindowModality(QtCore.Qt.ApplicationModal)
        PyiToolChoosePyEnv.resize(396, 262)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        PyiToolChoosePyEnv.setFont(font)
        self.verticalLayout = QtWidgets.QVBoxLayout(PyiToolChoosePyEnv)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lw_py_envs = QtWidgets.QListWidget(PyiToolChoosePyEnv)
        self.lw_py_envs.setObjectName("lw_py_envs")
        self.verticalLayout.addWidget(self.lw_py_envs)

        self.retranslateUi(PyiToolChoosePyEnv)
        QtCore.QMetaObject.connectSlotsByName(PyiToolChoosePyEnv)

    def retranslateUi(self, PyiToolChoosePyEnv):
        _translate = QtCore.QCoreApplication.translate
        PyiToolChoosePyEnv.setWindowTitle(_translate("PyiToolChoosePyEnv", "选择Python环境"))
