# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'show_downloading.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_downloading(object):
    def setupUi(self, downloading):
        downloading.setObjectName("downloading")
        downloading.resize(350, 660)
        downloading.setMinimumSize(QtCore.QSize(350, 660))
        downloading.setMaximumSize(QtCore.QSize(350, 660))
        self.horizontalLayout = QtWidgets.QHBoxLayout(downloading)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tw_downloading = QtWidgets.QTableWidget(downloading)
        self.tw_downloading.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tw_downloading.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tw_downloading.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tw_downloading.setCornerButtonEnabled(False)
        self.tw_downloading.setObjectName("tw_downloading")
        self.tw_downloading.setColumnCount(2)
        self.tw_downloading.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tw_downloading.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_downloading.setHorizontalHeaderItem(1, item)
        self.tw_downloading.horizontalHeader().setHighlightSections(False)
        self.tw_downloading.horizontalHeader().setStretchLastSection(True)
        self.tw_downloading.verticalHeader().setHighlightSections(False)
        self.horizontalLayout.addWidget(self.tw_downloading)

        self.retranslateUi(downloading)
        QtCore.QMetaObject.connectSlotsByName(downloading)

    def retranslateUi(self, downloading):
        _translate = QtCore.QCoreApplication.translate
        downloading.setWindowTitle(_translate("downloading", "下载列表"))
        item = self.tw_downloading.horizontalHeaderItem(0)
        item.setText(_translate("downloading", "下载项"))
        item = self.tw_downloading.horizontalHeaderItem(1)
        item.setText(_translate("downloading", "下载状态"))
