# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_entrance.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_main_entrance(object):
    def setupUi(self, main_entrance):
        main_entrance.setObjectName("main_entrance")
        main_entrance.resize(240, 41)
        self.centralwidget = QtWidgets.QWidget(main_entrance)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.uiPushButton_pkg_mgr = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uiPushButton_pkg_mgr.sizePolicy().hasHeightForWidth())
        self.uiPushButton_pkg_mgr.setSizePolicy(sizePolicy)
        self.uiPushButton_pkg_mgr.setIconSize(QtCore.QSize(32, 32))
        self.uiPushButton_pkg_mgr.setFlat(True)
        self.uiPushButton_pkg_mgr.setObjectName("uiPushButton_pkg_mgr")
        self.horizontalLayout.addWidget(self.uiPushButton_pkg_mgr)
        self.uiPushButton_pyi_tool = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uiPushButton_pyi_tool.sizePolicy().hasHeightForWidth())
        self.uiPushButton_pyi_tool.setSizePolicy(sizePolicy)
        self.uiPushButton_pyi_tool.setIconSize(QtCore.QSize(32, 32))
        self.uiPushButton_pyi_tool.setFlat(True)
        self.uiPushButton_pyi_tool.setObjectName("uiPushButton_pyi_tool")
        self.horizontalLayout.addWidget(self.uiPushButton_pyi_tool)
        self.uiPushButton_index_mgr = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uiPushButton_index_mgr.sizePolicy().hasHeightForWidth())
        self.uiPushButton_index_mgr.setSizePolicy(sizePolicy)
        self.uiPushButton_index_mgr.setIconSize(QtCore.QSize(32, 32))
        self.uiPushButton_index_mgr.setFlat(True)
        self.uiPushButton_index_mgr.setObjectName("uiPushButton_index_mgr")
        self.horizontalLayout.addWidget(self.uiPushButton_index_mgr)
        self.uiPushButton_pkg_dload = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uiPushButton_pkg_dload.sizePolicy().hasHeightForWidth())
        self.uiPushButton_pkg_dload.setSizePolicy(sizePolicy)
        self.uiPushButton_pkg_dload.setIconSize(QtCore.QSize(32, 32))
        self.uiPushButton_pkg_dload.setFlat(True)
        self.uiPushButton_pkg_dload.setObjectName("uiPushButton_pkg_dload")
        self.horizontalLayout.addWidget(self.uiPushButton_pkg_dload)
        self.uiPushButton_cloudfunction = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uiPushButton_cloudfunction.sizePolicy().hasHeightForWidth())
        self.uiPushButton_cloudfunction.setSizePolicy(sizePolicy)
        self.uiPushButton_cloudfunction.setIconSize(QtCore.QSize(32, 32))
        self.uiPushButton_cloudfunction.setFlat(True)
        self.uiPushButton_cloudfunction.setObjectName("uiPushButton_cloudfunction")
        self.horizontalLayout.addWidget(self.uiPushButton_cloudfunction)
        self.uiPushButton_settings = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uiPushButton_settings.sizePolicy().hasHeightForWidth())
        self.uiPushButton_settings.setSizePolicy(sizePolicy)
        self.uiPushButton_settings.setIconSize(QtCore.QSize(32, 32))
        self.uiPushButton_settings.setFlat(True)
        self.uiPushButton_settings.setObjectName("uiPushButton_settings")
        self.horizontalLayout.addWidget(self.uiPushButton_settings)
        main_entrance.setCentralWidget(self.centralwidget)

        self.retranslateUi(main_entrance)
        QtCore.QMetaObject.connectSlotsByName(main_entrance)

    def retranslateUi(self, main_entrance):
        _translate = QtCore.QCoreApplication.translate
        main_entrance.setWindowTitle(_translate("main_entrance", "Awespykit"))
        self.uiPushButton_pkg_mgr.setToolTip(_translate("main_entrance", "包管理器\n"
"用于管理不同 Python 环境中的包/库/模块"))
        self.uiPushButton_pyi_tool.setToolTip(_translate("main_entrance", "程序打包工具\n"
"使用 Pyinstaller 将 Python 程序打包成 exe 文件"))
        self.uiPushButton_index_mgr.setToolTip(_translate("main_entrance", "Pip 源设置工具\n"
"设置不同的镜像源为 pip 全局索引源，加快 pip 下载速度"))
        self.uiPushButton_pkg_dload.setToolTip(_translate("main_entrance", "模块安装包下载器\n"
"用于下载 Python 各种第三方包/库/模块的离线安装包"))
        self.uiPushButton_cloudfunction.setToolTip(_translate("main_entrance", "云函数部署包打包工具\n"
"用于将云函数项目打包为云函数部署包"))
        self.uiPushButton_settings.setToolTip(_translate("main_entrance", "工具箱的设置菜单\n"
"包含界面风格设置、关于菜单"))
