# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'environch.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_environch(object):
    def setupUi(self, environch):
        environch.setObjectName("environch")
        environch.setWindowModality(QtCore.Qt.ApplicationModal)
        environch.resize(396, 262)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        environch.setFont(font)
        self.verticalLayout = QtWidgets.QVBoxLayout(environch)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lw_env_list = QtWidgets.QListWidget(environch)
        self.lw_env_list.setObjectName("lw_env_list")
        self.verticalLayout.addWidget(self.lw_env_list)

        self.retranslateUi(environch)
        QtCore.QMetaObject.connectSlotsByName(environch)

    def retranslateUi(self, environch):
        _translate = QtCore.QCoreApplication.translate
        environch.setWindowTitle(_translate("environch", "选择 Python 环境"))
