# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'environch.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_environch(object):
    def setupUi(self, environch):
        environch.setObjectName("environch")
        environch.setWindowModality(QtCore.Qt.ApplicationModal)
        environch.resize(380, 200)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        environch.setFont(font)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(environch)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.lw_env_list = QtWidgets.QListWidget(environch)
        self.lw_env_list.setObjectName("lw_env_list")
        self.verticalLayout.addWidget(self.lw_env_list)
        self.label = QtWidgets.QLabel(environch)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(environch)
        QtCore.QMetaObject.connectSlotsByName(environch)

    def retranslateUi(self, environch):
        _translate = QtCore.QCoreApplication.translate
        environch.setWindowTitle(_translate("environch", "选择 Python 环境"))
        self.label.setText(_translate("environch", "如果此处没有可选择的 Python 环境则需先到<包管理器>中添加。"))
