# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'showdload.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_showdload(object):
    def setupUi(self, showdload):
        showdload.setObjectName("showdload")
        showdload.setWindowModality(QtCore.Qt.ApplicationModal)
        showdload.resize(320, 600)
        showdload.setMinimumSize(QtCore.QSize(320, 600))
        self.horizontalLayout = QtWidgets.QHBoxLayout(showdload)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tw_downloading = QtWidgets.QTableWidget(showdload)
        self.tw_downloading.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tw_downloading.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.tw_downloading.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tw_downloading.setCornerButtonEnabled(False)
        self.tw_downloading.setObjectName("tw_downloading")
        self.tw_downloading.setColumnCount(2)
        self.tw_downloading.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tw_downloading.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_downloading.setHorizontalHeaderItem(1, item)
        self.tw_downloading.horizontalHeader().setHighlightSections(False)
        self.tw_downloading.horizontalHeader().setStretchLastSection(True)
        self.tw_downloading.verticalHeader().setHighlightSections(False)
        self.horizontalLayout.addWidget(self.tw_downloading)

        self.retranslateUi(showdload)
        QtCore.QMetaObject.connectSlotsByName(showdload)

    def retranslateUi(self, showdload):
        _translate = QtCore.QCoreApplication.translate
        showdload.setWindowTitle(_translate("showdload", "下载列表"))
        item = self.tw_downloading.horizontalHeaderItem(0)
        item.setText(_translate("showdload", "下载项"))
        item = self.tw_downloading.horizontalHeaderItem(1)
        item.setText(_translate("showdload", "下载状态"))
